export interface ProgramInterface {
  pgIdx: string,
  type: string,
  pgTitle: string,
  pgAppSttDate: string,
  pgAppEndDate: string,
  pgSttDate: string,
  pgEndDate: string,
  pgWklyTimes: string,
  pgAppNow: string,
  pgPlace: string,
  pgStatus: string,
  pgIsApply: string,
  pgAppLimit: string,
  pgOrgan: string,
  pgContact: string,
  pgTarget: string,
  pgTakenTimes: string,
  pgProcWay: string,
  pgMainAct: string,
  pgExpect: string,
}
