export interface SurveyListInterface {
    pgIdx: string,
    pgTitle: string,
    pgType: string,
    isPreOpen: string,
    preSolvedCount: string,
    preAllCount: string,
    svPreData: [],
    isIngOpen: string,
    ingSolvedCount: string,
    ingAllCount: string,
    svIngData: [],
    isEndOpen: string,
    endSolvedCount: string,
    endAllCount: string,
    svEndData: string,
}
